react-rails.gemspec, test/jsxtransform_test.rb
Upgrading react-source to 0.12.2
Tests were failing when expecting a single quoted string in transformed JSX. It looks like this can be traced back to facebook/react@eddbb0c, so I'm updating the expectation to a double-quoted string—see 71a01bc.
=> Upgrade react-source to 0.12.2

lib/assets/javascripts/react_ujs.js
The current code always uses Turbolinks events if it is loaded, but this
doesn't mean it is supported by the browser. This change checks if
turbolinks is supported and otherwise uses the native event handlers.
Without this fix ujs components are not rendered in IE8.
=> Only use turbolinks events if supported

react-rails.gemspec
react-rails is now hosted under 'reactjs' organization.
=> Fix link to homepage

lib/react/rails/railtie.rb
This has been broken for a while :grimacing: 
Basically, the code has been passing the wrong variable in, so the render pool size was always defaulting to `10`.
=> Correctly pass `max_renderers` config to setup

react-rails.gemspec
Looks like some bug in `coffee-script-source 1.9.0` 
https://github.com/jashkenas/coffeescript/issues/3829
curious if this will do the trick
=> chore(gems) use coffee-script-source 1.8.0

react-rails.gemspec
They've published coffee-script-source 1.9.1, let's see if that resolves the test failure issue
=> fix(gems) add coffeescript 1.9.1

lib/react/rails/railtie.rb
It seems like we have a problem with initializers:
- not reloading when testing #155
- "Addons is undefined" #148 
- react source files aren't copied #175
Messing with the initializers has been recommended before: 
- changing the `group:` #40 
- initialize after sprockets #36 (However that initializer [no longer exists](https://github.com/rails/sprockets-rails/issues/227))
But I couldn't find much about how initializers run, just an [offhand mention in the Railtie docs](http://edgeapi.rubyonrails.org/classes/Rails/Railtie.html) (do you know of anything better?). 
I did find a couple of examples of `group: :all` in the wild:
- [sass-rails does it](https://github.com/rails/sass-rails/blob/master/lib/sass/rails/railtie.rb)
- [ember-rails does …
=> fix(Railtie) make sure initializers always run

lib/assets/javascripts/react_ujs.js.erb
Don't remove wrappers after unmounting nodes because it breaks Turbolinks cache (#159). 
I can't find the PR where this was added, I would like to go back and see why, but now I can't find it :( 
Anyways, I was surprised this broke because I remember we have a test for navigating back and forth and making sure things mount ok. I added a test and found that in fact, Turbolinks isn't supported in the test environment: 
```  ruby
test 'turbolinks works in test'  do
assert(page.evaluate_script('Turbolinks.supported')) # fails
end
```
So, the test doesn't guarantee turbolinks works :(
=> fix(ujs) don't remove nodes after unmounting components

lib/assets/javascripts/react_ujs.js.erb
This PR address an edge case when there's bad written JavaScript before requiring `react_ujs`. Given how automatic semi-colon insertion works in JavaScript, an IIFE can be evaluated as a function call instead of a evaluation context.
This happened to me using `browserify-rails` and requiring `react_ujs` just after doing `require('React')`, but it can happen in multiple scenarios.
=> adding semi-colon in front of IIFE

.gitignore, README.md, lib/assets/javascripts/react_ujs.js.erb, lib/react-rails.rb, lib/react/console.rb, lib/react/rails/railtie.rb, lib/react/renderer.rb, test/dummy/app/assets/javascripts/components/TodoListWithConsoleLog.js.jsx, test/dummy/app/assets/javascripts/example2.js.jsx.coffee, test/dummy/app/controllers/server_controller.rb, test/dummy/app/views/server/console_example.html.erb, test/dummy/app/views/server/console_example_suppressed.html.erb, test/dummy/app/views/server/show.html.erb, test/dummy/config/routes.rb, test/jsxtransform_test.rb, test/server_rendered_html_test.rb
Addresses reactjs/react-rails#122.  Adds a new `replay_console: true` option, to be used in conjunction with `prerender: true` on the `react_component` view helper (can assist in debugging).  Updated README and added integration tests.
=> Replay console logging on client after server prerender

README.md
It seemed to me that the readme had grown paragraph-by-paragraph for quite some time and was due for some reorganization :)
I hope that more structure and shorter overall length will help users find what they are looking for. My approach was:
- Group information by feature
- Put configurations near the feature they configure
- For nearly all users, UJS & view helper are closely linked, so put them close to each other
- Add table-of-contents-like links at the top of the readme
- Increase content related to FAQs, decrease less-recently-requested info
- prerender issues, eg no `document`, global scope required, include your dependencies
- lots of mentions of restarting your dev server 
- shrink docs related to drop-in copies of JS libs
You can see a rendered version of it here: …
=> chore(docs) reorganize readme

lib/react/renderer.rb, test/react_renderer_test.rb
The latest version of execjs now includes backtraces in Javascript errors - this makes debugging problems much easier!
=> Include a stacktrace from execjs

README.md
It's totally cool to encourage people to use master, but attaching a "pre" version number is pretty confusing, as it implies that there is a branch, tag, or published gem somewhere.
This hopefully removes that confusion and just implies that you're pulling from master.
=> Point Gemfile instructions at GitHub master instead of nonexistent prerelease version

react-rails.gemspec
Much apologies if this has already been addressed. I’ve seen a few similar issues (https://github.com/reactjs/react-rails/pull/167#issuecomment-73306684, https://github.com/reactjs/react-rails/pull/168), but no apparent resolution. 
There seems to be a known issue with the latest version of `coffee-script-source` outlined in https://github.com/jashkenas/coffeescript/issues/382.
The `react-rails` gemspec specifies a `~>1.9` version of `coffee-script-source`, which makes it impossible to back out of its most recent version, in order to avoid the errors (for example, if you want to specify `~>1.8` in your app). 
This change lowers the dependency version in the `react-rails` gemspec so that a user can specify a lower working version.
=> Lower the coffee-script-source version specifier

lib/assets/javascripts/react_ujs.js.erb, test/dummy/app/views/pages/show.html.erb, test/view_helper_test.rb
I'm working on an app where we need to be able to manually unmount specific components when a modal is closed. This PR adds a `searchSelector` argument to `ReactRailsUJS.mountComponents` and `ReactRailsUJS.unmountComponents` which lets you target specific elements. 
This is similar to https://github.com/reactjs/react-rails/pull/91. This functionality has been listed as a goal for 1.0 (https://github.com/reactjs/react-rails/issues/133) but the author of #91 hasn't responded in two months so I opened this PR.
=> Use a selector to mount and unmount components at a given node

README.md, VERSIONS.md, lib/react/rails/version.rb, react-rails.gemspec
As expressed in #133, we need a way to better express how gem versions and react versions compare. 
I've taken a page from [jquery-rails](https://github.com/rails/jquery-rails)'s book and added a `VERSIONS.md` file with info about bundled versions. I also put information there about other ways of controlling the React version.
Right now, the update plan is pretty low-tech: I added comments to gem version and `react-source` version to remind anyone to update `VERSIONS.md`. In my opinion, this is better than what we have now and good enough for the time being. 
If you prefer, we could add a rake task for updating the react version. I think it's overkill (more maintenance overhead than the comments, more likely to break in the future), but jquery-rails does something similar and I'm open to …
=> feat(versions) add VERSIONS.md for gem/React versions

README.md, VERSIONS.md, lib/react/rails/version.rb, react-rails.gemspec
- Remove pre-`1.0` language from Readme
- Update `React::Rails::VERSION` and `VERSIONS.md` 
- Gemfile cleanup: alphabetize dependencies
=> bump to 1.0

README.md
The doc bloc isn't required in the bundled version of React. I think this sentiment is no longer relevant.
=> docs(README): remove CoffeeScript doc bloc section

README.md, VERSIONS.md
There’s a typo in `VERSIONS.md` and a few small spots where the documentation can be a bit more consistent with colon usage and inline code spans (when referring to `react-rails` etc). Nothing major at all, just some tiny things I noticed :wink:
=> Fix a documentation typo and several small proofing edits

react-rails.gemspec
This is related to [#243](https://github.com/reactjs/react-rails/pull/243/files)
I am using react-rails as dependency in a gem I created and running rspec in that gem throws the following error:
$ rspec
/Users/gbanis/.rvm/gems/ruby-2.0.0-p598/gems/react-rails-0.13.0.0/lib/react/jsx/template.rb:1:in `require': cannot load such file -- tilt (LoadError)
from /Users/gbanis/.rvm/gems/ruby-2.0.0-p598/gems/react-rails-0.13.0.0/lib/react/jsx/template.rb:1:in `<top (required)>'
from /Users/gbanis/.rvm/gems/ruby-2.0.0-p598/gems/react-rails-0.13.0.0/lib/react/jsx.rb:3:in `require'
from /Users/gbanis/.rvm/gems/ruby-2.0.0-p598/gems/react-rails-0.13.0.0/lib/react/jsx.rb:3:in `<top (required)>'
from /Users/gbanis/.rvm/gems/ruby-2.0.0-p598/gems/react-rails-0.13.0.0/lib/react-rails.rb:1:in `require'
from …
=> Rspec tests fail due to `tilt` dependency

react-rails.gemspec
Hi!
Just a quick change to make license-finding tools like [license_finder][0] happier based off [industry standards][1].
Thanks!
[0]: https://github.com/pivotal/LicenseFinder
[1]: https://spdx.org/licenses/
=> Use standard shortcode for Apache-2.0

lib/react/rails/railtie.rb
Followup to https://github.com/reactjs/react-rails/pull/254
See https://github.com/reactjs/react-rails/pull/254#issuecomment-98846865
cc  rmosolgo
=> Sprockets cache expiration based on react-rails settings

README.md
Oops, forgot about the fact that my changes to server rendering would make the home page out of sync with rubygems. I think that might be what's happening in #265.
Soon I'll push `1.1` but I think this note will help for now.
=> fix(readme) add note about API version

lib/react/rails/railtie.rb
Possible fix for https://github.com/reactjs/react-rails/issues/249#issuecomment-102529896
=> Set the assets version from an initializer

lib/react/rails/view_helper.rb, lib/react/server_rendering.rb, lib/react/server_rendering/sprockets_renderer.rb, test/react/rails/view_helper_test.rb, test/react/server_rendering/sprockets_renderer_test.rb, test/react/server_rendering_test.rb
My first API was shoving `prerender:` into the props hash, but obviously that doesn't work if props isn't a hash! 
So instead, pass `prerender_options` along through the ServerRendering pipeline. In theory, a render could take any options. 
`SprocketsRenderer` looks for `:static`, to use `React.renderToStaticMarkup`
=> fix(prerender) accept string props

react-rails.gemspec
Same issue as #243 and #248.
This is a greater issue than just Rspec failing. rails g scaffold and several other commands that touch the dependency fail.
=> Add `tilt` dependency

README.md, lib/react/jsx.rb, lib/react/jsx/template.rb, lib/react/jsx/transformer.rb, test/react/jsx_test.rb, test/react_test.rb, test/test_helper.rb
Simplifying the `JSX` module and providing the feature from #239 
- Use an instance of `JSX::Transformer` for transforming JSX
- `JSX.transform_options` are initialization options for `Transformer`
- feature: allow custom JSX files by passing `asset_path:` config (or even overriding `Transformer#jsx_transform_code` :grimacing: )
=> refactor(JSX::Transformer) use Transformer class; allow asset_path config

lib/react/server_rendering/sprockets_renderer.rb
Always indent one space inside <<-JS heredocs, rather than indenting in
some places and not in others
=> Make indentation in heredocs consistent

README.md, lib/react/jsx.rb, lib/react/jsx/babel_transformer.rb, lib/react/jsx/jsx_transformer.rb, react-rails.gemspec, test/dummy/config/environments/test.rb, test/generators/component_generator_test.rb, test/react/jsx_test.rb, test/test_helper.rb
- Added new BabelTransformer to start performing transformation using ruby-babel-transpiler
- Make new BabelTransformer the default transformer
- README changes to reflect new Babel Transformer
- Added deprecation warning for usage of old transformer options
- Move old transformer to JSXTransformer
- Fixed  component generator test after changes to new transformer
Fixes #292, #278
=> New Babel Transformer

lib/react/server_rendering.rb, lib/react/server_rendering/exec_js_renderer.rb, lib/react/server_rendering/sprockets_renderer.rb, test/react/server_rendering/exec_js_renderer_test.rb, test/react/server_rendering/sprockets_renderer_test.rb
This `ExecJSRenderer` was created while [testing server rendering performance](https://github.com/reactjs/react-rails/pull/290) and I thought it might be a chance to reorganize server rendering code. In this branch: 
- __`ExecJSRenderer`__ is basically a wrapper around ExecJS
- __`SprocketsRenderer`__ is an `ExecJSRenderer` which fetches source JS from the asset pipeline & enables "console replay"
What do you think?
- ExecJSRenderer was great for testing performance. I'm not sure what other use it could have but it might come in handy again. 
- ExecJSRenderer's `#before_render` and `#after_render` hooks add extensibility as requested in https://github.com/reactjs/react-rails/pull/253#issuecomment-102515499
- It demonstrates how Renderers fit into `react-rails`, maybe people will make …
=> feat(ExecJSRenderer) add ExecJSRenderer

README.md, lib/react/jsx.rb, lib/react/rails.rb, lib/react/rails/asset_variant.rb, lib/react/rails/railtie.rb, test/react/jsx/jsx_transformer_test.rb, test/react/jsx_test.rb, test/react/rails/asset_variant_test.rb, test/test_helper.rb
- Accept transformer class from config
- Right now the only way to do that was assign `React::JSX.transformer_class = ` which is ok with me, but I guess a Rails config is more normal 
- Don't reload the transformer in dev
- Make development match production
- If you change your JSX config, you'll need to restart the app anyways 
- Move JSXTransformerTest 
- one class, one file: works nice with Guard, makes it easy to find the tests for a class
- (I know not all of react-rails is on that pattern yet but i'm working on it :) 
- fix(ServerRendering) default pool_size of 1; document deadlock & ther… 
- based on findings from #290  
- refactor(AssetVariant) extract asset build & path logic
- just want to DRY it up and get logic out of the Railtie
=> Config & initialization fixes

lib/react/rails/engine.rb, lib/react/rails/railtie.rb
- Assets version and register_engine have been moved from app.assets to app.config.assets on sprockets
- Added a check to make sure to use proper asset object when calling version, register_engine, etc
=> Fix running on sprockets-rails master

README.md, lib/assets/javascripts/react_ujs.js.erb
Removing calls to ReactRailsUJS.unmountComponents on window unload for traditional apps using full page refreshes.  Unmounting components is unnecessary work on unload and causes undesirable ux when the DOM elements are removed causing repaints.  #296
=> remove unmountComponents on window unload

README.md, lib/generators/react/component_generator.rb, lib/generators/templates/component.es6.jsx, test/generators/es6_component_generator_test.rb
Here you go #316
I wanted to add some tests but basically it's just rerunning the same with another option. Should I dedupe the current one just for es6 or something else?
=> Add es6 option to generator

lib/react/rails/railtie.rb, test/dummy/config/application.rb, test/dummy/config/initializers/react.rb, test/react_test.rb
The standard config/initializers are only run after `railtie#before_initialize`, but we have to build the asset paths before `railtie#after_initialize` since at that point Sprockets has already frozen the asset paths.
This PR moves the asset path build to a point in between `before_initialize` and `after_initialize`, after the standard initializers are run but before Sprockets freezes the environment.
Fixes #345
=> Reposition asset path build

README.md, lib/react/jsx.rb
I hope this will help people understand & improve react-rails! And help them find ways to extend it in the ways they want to, eg Flux-on-the-server, gon.
=> docs(readme) document some customization points

README.md
As per discussion in the [pull request for this feature](https://github.com/reactjs/react-rails/pull/329#issuecomment-136419566). :neckbeard: 
/cc @rmosolgo
=> Add documentation for controller component rendering

lib/assets/javascripts/react_ujs.js.erb, test/dummy/app/views/pages/show.html.erb, test/generators/install_generator_test.rb, test/react/rails/view_helper_test.rb
Extend possibility of findDOMNodes and as a consequence mountComponents. It allows to use it with an element which was inserted to the DOM tree without react.js. Example:
```
$(document).on('nested:fieldAdded', function(e) {
window.ReactRailsUJS.mountComponents(e.target);
});
```
Follow up from https://github.com/reactjs/react-rails/pull/340
=> Allow to pass DOM object as parent selector (second PR)

lib/assets/javascripts/react_ujs.js.erb
In 0.14, we now have `ReactDOM`. Prefer it for now to get rid of errors in the console.
=> Support ReactDOM in react_ujs

lib/assets/javascripts/react_ujs.js.erb
Same fix as #366, but for `unmountComponents`
=> Support ReactDOM in react_ujs for unmountComponents

lib/react/rails/view_helper.rb, test/react/rails/react_rails_ujs_test.rb, test/react/rails/view_helper_test.rb
Turns out there are some cases where the view helper will be used _without_ the Rails controller lifecycle:
- view tests (Rspec or ActionView::TestCase)
- the `cells` gem
In these cases, fall back to a plain instantiation of the helper implementation. (No `setup` or `teardown` in this case)
Also: 
- Move Capybara tests to `ReactRailsUJSTest` since they're really testing the UJS, not the `ViewHelper`
=> fix(ViewHelper) create a new helper in case controller wasn't used

README.md, lib/react/rails/controller_renderer.rb, test/dummy/app/controllers/server_controller.rb, test/server_rendered_html_test.rb
Currently, all custom attributes are sliced from options  when using the controller renderer, instead of forwarding it to the view helper, making it impossible to set a custom class name or id.
This patch changes the behaviour to act more like render_component.
=> Add ability to render custom attributes from the controller

README.md, lib/generators/react/component_generator.rb, lib/generators/templates/component.js.jsx.coffee, test/generators/coffee_component_generator_test.rb
Generate a CoffeScript component similar to what the --es6 option does.
Closes #351
=> Add --coffee option to component generator

README.md
Since React 0.12 the ES6 style syntax can be used with CoffeeScript classes as well. The docs should give a hint for this.
=> Update README to hint for newer syntax

lib/react/jsx.rb, lib/react/jsx/processor.rb, lib/react/rails/engine.rb, test/react/jsx/jsx_transformer_test.rb
Starting version 4 Sprockets is removing the `register_engine` method which registers JSX transformers using Tilt based templates breaking this gem for the current Rails 5 `master`. This has been deprecated since Sprockets version 3:
https://github.com/rails/sprockets/blob/master/UPGRADING.md
This PR adds a JSX Processor and registers it via `register_processor` as `application/jsx` mime type. Is there a reserved mime type for JSX templates?
=> Switch to the new Sprockets processor

lib/react/rails/engine.rb
Fixes https://github.com/reactjs/react-rails/issues/395 by adding `.es.jsx` and `.es6.jsx` extensions.
See https://github.com/reactjs/react-rails/issues/395#issuecomment-159058805 for details.
=> Fix ECMAScript compilation

README.md, lib/react/rails/component_mount.rb, lib/react/rails/railtie.rb, lib/react/server_rendering/sprockets_renderer.rb, test/react/rails/component_mount_test.rb
Camle-Case in es6.jsx:
```
static propTypes = {
form: PropTypes.object,
errorMessages: PropTypes.array,
defaultFieldValues: PropTypes.object
}
```
I must be camle-case  in Rails: 
```
props = {form: {action: "new"}, errorMessages: ["errors1, errors2"], defaultFieldValues:  {some: "value"}}
```
I think it's better in Rails:
```
props = {form: {action: "new"}, error_messages: ["errors1, errors2"], default_field_values: {some: "value"}}
```
=> Snake-Case key to Camel-Case key for props when server render

lib/generators/react/install_generator.rb
=> fixed insert many require react when the file has many require_tree

react-rails.gemspec
Help developers know what's new using `bundle open react-rails` etc after a `bundle update` instead of having to navigate to github.
=> Include CHANGELOG in gem

lib/react/rails/controller_lifecycle.rb
`before_filter` is deprecated in Rails 5 and will disappear in 5.1
This change begins using `before_action`, with a fallback to `before_filter` if `before_action` is not available.
closes #404
=> Support controller callbacks for Rails 3..5

lib/react/server_rendering/environment_container.rb, lib/react/server_rendering/exec_js_renderer.rb, lib/react/server_rendering/manifest_container.rb, lib/react/server_rendering/sprockets_renderer.rb, test/react/server_rendering/manifest_container_test.rb, test/react_test.rb, test/test_helper.rb
Previously, `SprocketsRenderer` would live-compile assets, even in production. However, this is _impossible_ in Rails 5 (not just improper) because there _is no_ `Sprockets::Environment` at `Rails.application.assets`. 
Instead, there is a `Sprockets::Manifest` at `Rails.application.assets_manifest` which tells where each file's compiled counterpart is. 
So, if the Sprockets::Environment isn't available, use the manifest.
=> Fix(SprocketsRenderer) support Sprockets::Manifest if assets were precompiled

.travis.yml, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.gemfile, lib/assets/javascripts/react_ujs.js, lib/assets/javascripts/react_ujs_event_setup.js, lib/assets/javascripts/react_ujs_mount.js, lib/assets/javascripts/react_ujs_native.js, lib/assets/javascripts/react_ujs_turbolinks.js, lib/assets/javascripts/react_ujs_turbolinks_classic.js, lib/assets/javascripts/react_ujs_turbolinks_classic_deprecated.js, test/react/rails/react_rails_ujs_test.rb, test/react/server_rendering/manifest_container_test.rb, test/test_helper.rb
Turbolinks 5 might have some different APIs to support. We want to support all of them!
I think this a good chance to split the UJS into different files. I hope it will make it easier for new people to find the code they want to change & work on it. Also, you could "mix & match" the UJS if you didn't want certain parts of it.
=> Refactor UJS, support Turbolinks 5

lib/assets/javascripts/react_ujs_mount.js, test/dummy/app/views/pages/show.html.erb, test/react/rails/react_rails_ujs_test.rb
* this is to support the case where you want to mount or unmount a single component
with a known ID that is a sibling of one or more components that you don't want to affect
* currently, if you pass in a parent element to use a scope, it will mount/unmount
all components underneath
* you also can't pass in the known ID of a mounted component because the selector
it constructs assumes the react element is a child
The context for this change is we have a custom view helper that goes through a bunch of hoops to properly render React components used in older Rails pages that replace portions of their page with ajax and the Protoype/jQuery helpers. We need a way to mount components that are inserted into the page this way and we have the element's IDs. Unfortunately, none of the existing …
=> add ability to pass in a custom selector function to mountComponents

lib/generators/react/install_generator.rb, test/generators/install_generator_test.rb
When used `rails g react:install`, it generated modified `application.js` as given below.
```diff
//
//= require jquery
//= require jquery_ujs
-//= require turbolinks
+//= require turbolinks//= require react
+//= require react_ujs
+//= require components
+
```
Made changes to have inserted content on the new line.
=> Fixing install generator to have inserted content properly on the new Line

lib/react/rails/component_mount.rb, test/react/rails/component_mount_test.rb
In it's current implementation `camelize_props` only supports nested hashes.
{foo_bar: {user: {id: 1, user_name: 'ryan'}}}
converts to 
{fooBar: {user: {id: 1, userName: 'ryan'}}
However nested arrays that contain hashes are left unchanged.
{foo_bar: [{id: 1, user_name: 'ryan'}, {id: 2, user_name: 'Matt'}]}
converts to
{fooBar: [{id: 1, user_name: 'ryan'}, {id: 2, user_name: 'Matt'}]}
This PR adds support for nested arrays that contain hashes. After this commit it converts to:
{fooBar: [{id: 1, userName: 'ryan'}, {id: 2, userName: 'Matt'}]}
=> Add support for nested arrays in camelize_props

lib/react/server_rendering/sprockets_renderer.rb, lib/react/server_rendering/yaml_manifest_container.rb, test/react/server_rendering/yaml_manifest_container_test.rb, test/test_helper.rb
Based on discussions with @rmosolgo this PR restores full support for Rails 3.2, specifically server rendering with precompiled assets.
Closes #483 and Closes #484 
Added tests pass but `react_test/precompiling assets works` throws an error when trying to call `clear_precompiled_assets`
=> Add YamlManifestContainer for Rails 3.2 server rendering support

Appraisals, gemfiles/rails_3.2.gemfile, lib/react/server_rendering/sprockets_renderer.rb, test/react/server_rendering/manifest_container_test.rb, test/react/server_rendering/sprockets_renderer_test.rb, test/test_helper.rb
Hi @rmosolgo!
Unfortunately I found an issue with [the code we just merged](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L67) that checks the Rails version in `SprocketsRenderer`. Rather than reference the top level `Rails` class using `::Rails` I mistakenly referenced plain old `Rails` which in this context is `React::Rails`. I expected that to be tested but on second glance saw it was not. This PR fixes that reference plus adds test coverage for `SprocketsRenderer` when `Rails.application.config.assets.compile == false`.
I've also fixed a few issues I found with the test helper's `precompile_assets` method. Let me know what you think. :dog:
=> Fix Rails reference in SprocketsRenderer

lib/react/server_rendering/sprockets_renderer/console_replay.js, test/react/server_rendering/sprockets_renderer_test.rb
Code from Ruby string days was still in the standalone JS file and it caused browsers to complain. Tightened up the regex to catch this in tests.
Fixes https://github.com/reactjs/react-rails/issues/494
=> Fix bug with console replay and carriage returns

lib/react/rails/component_mount.rb, test/react/rails/component_mount_test.rb
Should result in cleaner markup in cases where the client side React won't be rendered anyways.
Alternatively, this could be an option but it seems like a sensible default to me.
=> When a static render is done, don't include react class/props

lib/assets/javascripts/react_ujs.js, lib/assets/javascripts/react_ujs_event_setup.js, lib/assets/javascripts/react_ujs_pjax.js
Thanks to @QuantumKing for actually doing the work on this!
=> Pjax support 2

.travis.yml, Rakefile, react-rails.gemspec
=> fix(build): use alternate url for phantomjs to avoid 403 throttling errors

lib/assets/javascripts/react_ujs_turbolinks.js
This event is a bit later, it looks better to do it this way
=> fix(JS): unmount components during 'turbolinks:before-render' for Turbolinks 5

lib/react/rails/railtie.rb
In rails/rails@d3c9d808e3e242155a44fd2a89ef272cfade8fe8, `ActionDispatch::Reloader.to_prepare` (and friends) were moved to `ActiveSupport`.
For now, they're only issuing a deprecation warning, but they're planning on dropping support in Rails 5.1.
> `DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead)`
I didn't have a great way to add a test for this, but the implementation seems pretty straightforward.  I've tested that the gem works with an app in development.  The app doesn't actually use server rendering, but it does boot and otherwise work great.
=> Fix Rails 5 .to_prepare deprecation warning

README.md
Haven't found in readme how to manually mount component in the end of ajax call. Googled answer here https://github.com/reactjs/react-rails/issues/173.
=> Add a tip on how to trigger UJS mounting from js

lib/assets/javascripts/react_ujs_mount.js
The Problem
-----------
Currently, if you use an invalid component name in `data-react-class`,
you get a React invariant error that only tells you that the component
class was undefined, but it doesn't actually help you fix the error. I
end up needing to scroll backwards in the stack trace until I find this
part of the `react_ujs_mount.js` code and inspect the value of
`className`
The Solution
------------
Throw a helpful error (and nice console log message) about an invalid
className at the moment we try to mount the component. You can even right-click
and `Reveal in Elements Panel` to see exactly where the element is in the DOM!
=> feat(UJS) show helpful error messages for missing components

lib/assets/javascripts/react_ujs_mount.js
With the update to Babel 6, modules are being exported differently. For
instance, the default module is now under a default key. This is
breaking things when using an expose loader with webpack. This adds a
check for that before trying to import the module.
=> Update to accept new babel 6 module exports

lib/react-rails.rb, lib/react.rb, lib/react/rails/component_mount.rb, test/react_asset_test.rb, test/react_test.rb
People might want to push props in some way other than the `react_component` helper, so make this behavior public (eg #530). Also, fixes a bug with nested arrays.
=> feat(React) expose camelize_props function

.travis.yml, gemfiles/rails_5.gemfile, gemfiles/rails_5_no_sprockets.gemfile, lib/react/rails/railtie.rb, react-rails.gemspec, test/dummy/app/assets/javascripts/components/PlainJSTodo.js, test/dummy/config/application.rb, test/dummy/config/environments/test.rb, test/react/jsx/jsx_transformer_test.rb, test/react/jsx_test.rb, test/react/rails/component_mount_test.rb, test/react/rails/react_rails_ujs_test.rb, test/react/server_rendering/exec_js_renderer_test.rb, test/react/server_rendering/sprockets_renderer_test.rb, test/react_asset_test.rb, test/server_rendered_html_test.rb, test/test_helper.rb
This is to combine #427 & #493 , I want to make sure they work together and see if any new testing can be added
=> Minimize rails dependency

lib/generators/react/ujs_generator.rb, test/generators/ujs_generator_test.rb
In a recent version, I split the UJS into many files, then `//= require` them together with Sprockets. This is great for code generation but bad for someone who wants to use the code in a non-Sprockets setup. 
Add `rails generate react:ujs --output=my/custom/react_ujs.js --turbolinks_classic_deprecated=false --pjax=false --native=false" for people who want to copy the UJS into their own setups.
=> feat(ujs) add react:ujs generator for customizing UJS

lib/react/rails/railtie.rb
This will remove the deprecation warning in sprockets 3.7.0+.
=> Use new syntax for sprocket 3.7.0+

lib/react/rails/railtie.rb, test/dummy/app/assets/javascripts/require_test/jsx_preprocessor_test.jsx, test/dummy/app/assets/javascripts/require_test/jsx_require_child_js.jsx, test/react/jsx/jsx_prepocessor_test.rb, test/react/jsx_test.rb, test/test_helper.rb
can you please check this PR @forelabs ?
=> add preprocessor to handle comment directives in sprocket 3.7.0+ , fixes #580

lib/react/jsx.rb, lib/react/jsx/sprockets_strategy.rb, lib/react/rails/railtie.rb, test/dummy/app/assets/javascripts/require_test/jsx_preprocessor_test.jsx, test/dummy/app/assets/javascripts/require_test/jsx_require_child_coffee.coffee, test/dummy/app/assets/javascripts/require_test/jsx_require_child_js.js, test/dummy/app/assets/javascripts/require_test/jsx_require_child_js.jsx, test/dummy/app/assets/javascripts/require_test/jsx_require_child_jsx.jsx, test/react/jsx/jsx_prepocessor_test.rb, test/test_helper.rb
We've had a few reports that our custom mime type doesn't work well with Sprockets 3.7+, I'm hoping this test case will turn up some failures
=> Require .js and .coffee from .jsx

lib/react/server_rendering/yaml_manifest_container.rb
Enable `react-rails` to locate the YAML manifest on applications using a different `config.assets.prefix`.
Related: #594, #597
=> Use assets prefix in yaml manifest path

lib/react/server_rendering/sprockets_renderer.rb, test/helper_files/WithoutSprockets.js, test/react/server_rendering/sprockets_renderer_test.rb
This enables additional code to be added to the Exec JS context when initialised.
Our app is consuming assets generated via Sprockets and Webpack, this option allows the Webpacked assets to injected along side the Sprockets assets for use in the ExecJS runtime.
=> Add code option to Sprockets Render

lib/assets/javascripts/react_ujs_mount.js
Using reserved words in dot property accessors is allowed in ES5,
but not in ES3. Android 2 throws `SyntaxError: Parse error` with `.default`
=> Use ['default'] property accessor, not .default

README.md
The links to transformers and plugins docs page were broken after the release of Babel 6. Replaced them with links to the official legacy documentation.
=> Fix broken links to babel's docs

README.md
> Reactrb is now a part of Ruby Hyperloop
http://ruby-hyperloop.io/reactrb/
=> Reactrb is now part of Ruby Hyperloop

lib/react/rails/view_helper.rb, test/dummy/app/views/pages/_component_with_inner_html.html.erb, test/react/rails/view_helper_test.rb
Capture block output to prevent double rendering.
references #640
=> Fix react_component helper usage with a block

lib/react/server_rendering/exec_js_renderer.rb, lib/react/server_rendering/sprockets_renderer.rb, test/react/server_rendering/sprockets_renderer_test.rb
Changes:
- Refactor a bit base renderer
- Refactor `SprocketsRenderer` to preserve custom prerender options
#639
=> #639 Pass pre-render options to callback functions

README.md, lib/react/rails/component_mount.rb, test/react/rails/component_mount_test.rb
This allows the use of camelize props on a case by case basis; useful if you want the option without breaking existing components
=> Allow `camelize_props` to be passed into component mounter

lib/react/rails/component_mount.rb, test/react/rails/component_mount_test.rb
A new feature in #642 was to pass `camelize_props: true` to override the default of `false`
This adds the ability to `camelize_props: false` to override the default of `true`.
=> feat(ComponentMount) allow overriding camelize_props=true with local false

README.md
Add a link to the free React on Rails course (https://learnetto.com/users/hrishio/courses/the-free-react-on-rails-5-course) to the Related Projects section in the README, as per email discussion with @rmosolgo.
=> Add link to free React on Rails course in README

react-rails.gemspec
coffee-script-source is not required to use this gem, so remove it from dependency.
=> remove coffee-script-source from dependency

README.md
=> Readme: Correct Markdown Link

lib/react/server_rendering.rb
If there _is_ an error message, we're not always getting it (eg #649)
=> try to get message from ProgramError

README.md, lib/react/rails/railtie.rb, test/server_rendered_html_test.rb
Using `FileUpdateChecker` will catch new files too, and we can expose an API for watching _any_ files (spoiler alert, I'm going to use this for webpacker 😆 )
=> feat(ServerRendering) reload when new files are added; support configurable reloader globs

README.md, react-rails.gemspec
The readme has been added to bit-by-bit for a long time. I've tried to reorganize it with: 
- A good table-of-contents at the top 
- Good proximity of related info & links 
- Good balance of length-to-importance
=> Redo Readme & update gemspec

lib/assets/javascripts/react_ujs.js, lib/react/rails/railtie.rb, lib/react/server_rendering/exec_js_renderer.rb, lib/react/server_rendering/sprockets_renderer.rb, lib/react/server_rendering/webpacker_manifest_container.rb, lib/react/server_rendering/yaml_manifest_container.rb, react_ujs/dist/react_ujs.js, react_ujs/index.js, react_ujs/src/getConstructor/fromGlobal.js, react_ujs/yarn.lock, test/dummy/app/controllers/server_controller.rb, test/dummy/app/javascript/components/GreetingMessage.js, test/dummy/app/javascript/components/Todo.js, test/dummy/app/javascript/components/TodoList.js, test/dummy/app/javascript/components/TodoListWithConsoleLog.js, test/dummy/app/javascript/components/WithSetTimeout.js, test/dummy/app/javascript/packs/server_rendering.js, test/dummy/app/views/server/show.html.erb, test/helper_files/TodoListWithUpdates.js, test/react/rails/component_mount_test.rb, test/react/rails/controller_lifecycle_test.rb, test/react/rails/pages_controller_test.rb, test/react/rails/react_rails_ujs_test.rb, test/react/rails/webpacker_test.rb, test/react/server_rendering/exec_js_renderer_test.rb, test/react/server_rendering/sprockets_renderer_test.rb, test/react/server_rendering/webpacker_manifest_container_test.rb, test/server_rendered_html_test.rb, test/support/webpacker_helpers.rb, test/test_helper.rb
Support server rendering based on a pack called `server_rendering.js`
=> Webpacker Server Rendering

.travis.yml, lib/react/server_rendering/webpacker_manifest_container.rb, test/dummy/app/javascript/components/GreetingMessage.js, test/react/rails/pages_controller_test.rb, test/react/rails/webpacker_test.rb, test/react/server_rendering/webpacker_manifest_container_test.rb, test/support/webpacker_helpers.rb
The trick was getting the websocket client code out of there, which i did with a regexp 😬
=> Support server-rendering from webpack-dev-server

lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/src/events/turbolinks.js, test/dummy/app/assets/config/manifest.js, test/dummy/app/assets/javascripts/turbolinks_only.js, test/dummy/app/controllers/pack_components_controller.rb, test/dummy/app/views/layouts/application.html.erb, test/react/rails/react_rails_ujs_test.rb, test/react/rails/webpacker_test.rb, test/test_helper.rb
=> fix(turbolinks) use good turbolinks events

lib/react/rails/component_mount.rb, lib/react/server_rendering.rb, lib/react/server_rendering/bundle_renderer/console_replay.js, test/dummy/app/javascript/components/TodoList.js, test/dummy/config/application.rb, test/react/server_rendering/bundle_renderer_test.rb
Fix #555 
If the console replay script is present in the mount tag, move it _outside_ the tag so that React doesn't complain when re-rendering inside the mount tag.
=> Fix console replay

README.md, lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/index.js, react_ujs/src/events/detect.js, react_ujs/src/events/native.js, react_ujs/src/events/pjax.js, react_ujs/src/events/turbolinks.js, react_ujs/src/events/turbolinksClassic.js, react_ujs/src/events/turbolinksClassicDeprecated.js, react_ujs/yarn.lock, test/dummy/package.json, test/dummy/yarn.lock
Oops, I discovered a circular dependency issue when upgrading my app to 2.0: 
- My sprockets bundle depends on my webpacker pack because the pack assigns `window.React`. 
- My webpacker pack has `require("react_ujs")` which checks the global context for events 
- At that time, Turbolinks is not present, so its events are not hooked up by UJS 
- For that reason, the webpacker pack depends on my sprockets bundle 😩 
With this branch, you can re-detect events at any time with `detectEvents()`. 
This way, I can add:
```js
$(function() {
// Now that turbolinks is loaded, hook up to it:
ReactRailsUJS.detectEvents()
})
```
=> fix(UJS) support cases when Turbolinks is loaded after UJS

lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/index.js, test/dummy/app/views/pages/show.html.erb, test/react/rails/controller_lifecycle_test.rb, test/react/rails/react_rails_ujs_test.rb
Looks like `findDOMNodes` has a typo in the argument name [here](https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L23). `selector` should be `searchSelector`. Since the incorrect value is used ALL components are unmounted when `findDOMNodes` is called from [unmountComponents](https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L100)
Updated argument name from `selector` to `searchSelector` [here](https://github.com/tannermares/react-rails/blob/4f65848239fd6665d8c4a8aa5878103764d83e11/react_ujs/index.js#L23)
I adding a spec. I'm not familiar with MiniTest or server side rendering and tried to implement the failure in the simplest way possible.
I believe the failing specs are from JS warnings the `rake react:update` caused. Looks like maybe the …
=> fix(ReactUjs): Fixed variable typo in findDOMNodes

react_ujs/src/events/detect.js
When using Turbolinks 5+, `ReactRailsUJS.detectEvents()` throws the following error when  removing the existing event handlers:
```
Uncaught TypeError: Cannot read property 'CHANGE' of undefined
at Object.teardown (turbolinksClassic.js?6757:9)
at module.exports (detect.js?5263:12)
at Object.detectEvents (index.js?c0e8:114)
```
Since Turbolinks 5 doesn't define `Turbolinks.EVENTS`, we can check for its existence before calling the classic teardown method.
=> check for turbolinks classic before teardown

lib/react/rails/railtie.rb, test/dummy/app/pants/yfronts.js, test/dummy/config/initializers/react.rb, test/react/rails/railtie_test.rb
Rails convention is now to load application config from initializers rather than `config/application.rb`. This PR makes it possible to specify`server_renderer_directories` (amongst other settings) and have the settings honoured by the file watcher. Previously some settings configured in an initializer were ignored as the file watcher block was run before initializers were loaded.
=> Configure watched files after rails initializers have loaded

README.md
The heading 'Camelize Props` has the id `camelize-props`, not `camelize_props`
=> Update camelize props anchor link in README

.travis.yml, Appraisals, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.0.5.gemfile, gemfiles/rails_4.0_with_therubyracer.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2_sprockets_2.gemfile, gemfiles/rails_4.2_sprockets_3.gemfile, gemfiles/rails_4.2_sprockets_4.gemfile, gemfiles/rails_5.1_sprockets_4.gemfile, gemfiles/rails_5_no_sprockets.gemfile, gemfiles/rails_5_no_sprockets_webpacker_1_1.gemfile, gemfiles/rails_5_no_sprockets_webpacker_1_x.gemfile, gemfiles/rails_5_no_sprockets_webpacker_2.gemfile, gemfiles/rails_5_no_sprockets_webpacker_3.gemfile, test/react/rails/pages_controller_test.rb, test/support/webpacker_helpers.rb
Hi again,
**Problem**
Noticed when 777 was merged to master, there was one timing problem test where in webpacker 3 
it's possible for it to say `Webpacker.dev_server.running? == true` before it was able to serve assets.
**Solution**
Check if the file is available in Webpacker 3 by opening it again, same as old method but using the dev_server methods. Also basically rewrote that loop while I was at it since we can just kill the PID and not need to do the `lsof` scan.
Also used the `param:` syntax for rails controller tests, it runs in Rails 3 and 5, and it also stops a deprecation warning so thats a freebie.
Also collected all the `MAJOR < 3` into one block, still not 100% sure about that patten but it seems to do a good job.
=> Cleanup tests, fix a broken test seed

CHANGELOG.md, VERSIONS.md, lib/react/rails/version.rb
@rmosolgo Thanks for the readme additions for a release. Do we need to publish to NPM even if there is no JS change?
If so I'll get set up there and let you know the details for it, and if not then I will try a gem release.
Believe I already updated the Changelog with both PRs merged since 2.2.1 so that *should* be everything.
In this release:
- #777 Webpacker 3 support
- #789 React 15.6.2 update.
Planned next point release:
- Any bugfixes.
- #790 React 16 update.
=> Prepare for 2.3.0 release

.travis.yml, README.md, react-rails.gemspec, test/test_helper.rb
Been having trouble installing the correct combinations of yarn, node (7.x), and phantomJS (2.1.1) to make the tests run smoothly on other computers. Even though I have the same versions, Cliver has decided not to load Phantom on certain machines.
Decided it would make developing this gem easier for other new people if everything they needed was in the Gemspec which you can do with headless chrome. Which is also the most up to date option.
Based on: https://robots.thoughtbot.com/headless-feature-specs-with-chrome and https://docs.travis-ci.com/user/gui-and-headless-browsers/
=> Update javascript driver to headless chrome

lib/generators/templates/component.js.jsx.coffee
Class with @ didn't work with export in footer (there is no need to set classes in global scope if they will be exported anyway, imho)
=> CoffeeScript React component generator fix

README.md
- updates instances that refer to the project name
This change updates the casing of "Webpacker" to be consistent with how it is used elsewhere, as in this [Webpacker announcement blog post](http://weblog.rubyonrails.org/2017/8/30/webpacker-3-0/).
=> Use title case for "Webpacker" in README

lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/package.json, react_ujs/src/events/detect.js, react_ujs/yarn.lock, test/dummy_sprockets/app/assets/config/manifest.js, test/dummy_sprockets/app/assets/javascripts/app_no_turbolinks.js, test/dummy_sprockets/app/controllers/pages_controller.rb, test/dummy_sprockets/app/views/layouts/app_no_turbolinks.html.erb, test/dummy_sprockets/config/application.rb, test/dummy_sprockets/config/routes.rb, test/react/rails/react_rails_ujs_test.rb
=> Fix Turbolinks Detection

lib/generators/react/component_generator.rb, test/generators/coffee_component_generator_test.rb
`webpacker:install:react` does not install createReactClass
Our generators should support Webpacker out of the box
Therefore we should use ES6 as the Webpacker default
https://reactjs.org/docs/react-without-es6.html
Fixes #820.
=> Use ES6 in ComponentGenerator for Webpacker

lib/assets/javascripts/react_ujs.js, package.json, react-rails.gemspec, react_ujs/dist/react_ujs.js, react_ujs/index.js, yarn.lock
Fixes #808 
Benchmarked on my companies private project and it's significantly faster for us!
Measured using 3 runs of [Chrome Lighthouse Audit](https://developers.google.com/web/updates/2017/05/devtools-release-notes#lighthouse)
I also felt cheeky enough to add myself as an author on the Gem if that's OK.
- 4.0s First Interactive
- 2.3s Perceived
- 3.0s First Interactive
- 2.7s Perceived
- 2.7s First Interactive
- 2.4s Perceived
=> Hydrate clientside

lib/react/server_rendering/webpacker_manifest_container.rb
Issue #739
In certain circumstances `webpacker-dev-server` includes the full path
(protocol and host with port) in the paths generated for the
packs/manifest.json file. This addition removes the protocol, host, and
port from the asset path when present allowing assets to be correctly
loaded.
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by …
=> :bug: Fix bug that prevents loading assets with `webpacker-dev-server`

CHANGELOG.md, VERSIONS.md, lib/react/rails/version.rb
Update version.md, version.rb, changelog.md
=> Prepare 2.4.1

CHANGELOG.md, CONTRIBUTING.md, lib/assets/javascripts/react_ujs.js, package.json, react_ujs/dist/react_ujs.js, react_ujs/index.js
Fixes #832
ReactDOM.hydrate() may not be defined for everyone, it will now use
hydrate if it is defined or fallback to render.
Will release a new package version followed by a gem version.
=> Fallback to Render if Hydrate is not defined

CHANGELOG.md, lib/assets/javascripts/react_ujs.js, lib/react/rails/component_mount.rb, react_ujs/dist/react_ujs.js, react_ujs/index.js
Allow react-rails to use ReactDOM.render in components created whose value for prerender is falsy (false, nil).
React gives a warning when a not pre-rendered component is not rendered using ReactDOM.render()
Following advise from #842 
A new html option has been added to use between the ReactDOM methods render() or hydrate().
render()
prerender not set or set to a falsy value
hydrate()
truthy value and not :static
=> :bug: Use ReactDOM.render instead of hydrate when prerender is falsy

README.md
We probably don't have `config/environments/application.rb` by default. Do you mean `config/application.rb` or `config/environments/production.rb` ?
```
$ rails new myapp
$ ls config/environments/
development.rb	production.rb	test.rb
```
=> Modify an example in the README

.codeclimate.yml
code climate is enabled for this repo - so when viewing the project page, you see this:
and then this  claim it would take 8 months of dev time to fix the tech debt.
Most of these are in the vendor/react asset files.
this adds a config file telling code climate to ignore vendor files
I think I identified these correctly, but I'm unsure.
If I've configured this right, it'll mean people are no longer greeted with warnings against using this gem
=> Ignore react library in code climate

README.md
add javascript_pack_tag helper to readme.
mention javascript_pack_tag helper in README.md,
so people check it by themselves instead 
creating a issue why their react component is not rendered
=> add javascript_pack_tag helper check to readme.

lib/react/server_rendering/exec_js_renderer.rb
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
As of 41721c5374925384adc8679aa007789b598de969, `exec_js_renderer` now needs `ReactRailsUJS` to appear in the global context, not `ReactDOM`. This commit updates an outdated comment to avoid confusion.
=> Fix misleading comment in exec_js_renderer

README.md
These commands will not work on rails < 5.0
```
$ rails webpacker:install
$ rails webpacker:install:react
```
=> fix(README): correct react:install for rails < 5.0

gemfiles/.bundle/config, lib/assets/javascripts/react_ujs.js, package.json, react_ujs/dist/react_ujs.js, react_ujs/src/events/detect.js, react_ujs/src/events/native.js, yarn.lock
Remove explicit JQuery hooks and use the browser's implementation
It was quite hard to replicate because in a standard rails install, Turbolink will be preferred, and once removed it just so happens that JQuery + (Rails/JQuery)_UJS is loaded in the correct order so you really have to get quite unlucky to trigger the bug at #762 
I'll likely release the NPM package (react_UJS) as a pre-release first, to make sure it actually plays nicely with more complex JQuery setups.
I don't have a complex example app to test it on therefore I will be relying on community input before merging.
Edit: Also Travis is being painful today, failed 3 times at random, passed 2nd or 3rd run, got a segfault, a Yarn timeout, and a GPG Key mismatch.
=> fix(#762): ensure react is mounted in Jquery3

lib/react/rails/controller_renderer.rb, test/dummy_sprockets/app/controllers/server_controller.rb, test/dummy_sprockets/config/routes.rb, test/dummy_webpacker1/app/controllers/server_controller.rb, test/dummy_webpacker1/config/routes.rb, test/dummy_webpacker2/app/controllers/server_controller.rb, test/dummy_webpacker2/config/routes.rb, test/dummy_webpacker3/app/controllers/server_controller.rb, test/dummy_webpacker3/config/routes.rb, test/server_rendered_html_test.rb
This allows the use of camelize props in controller actions.
```ruby
render component: 'Example', props: my_props, camelize_props: true
```
=> Controller camelize_props: true

README.md
Added a Typescript integration guide to README.md based on https://github.com/rails/webpacker/blob/master/docs/typescript.md
=> :memo: Add Typescript integration details

README.md, lib/generators/react/component_generator.rb, test/generators/component_generator_test.rb
Although the documentation references rendering components from sub-directories, the generator only allows generation of components in the `components/` directory. This PR adds `class_path` into the generated path, allowing use such as:
```
➜ rails g react:component frontend/my_component
Running via Spring preloader in process 45812
create  app/javascript/components/frontend/MyComponent.js
```
=> Add class_path to allow generated components to reside in subdirectories

lib/react/server_rendering/webpacker_manifest_container.rb
I found server-side rendering failed in our environment Rails 5.2, webpacker 4.0.0.pre.pre.2, webpack 4.4.1. The error message is following.
```
Failure/Error: <%= react_component("SearchFilter", {}, {prerender: true}) %>
ActionView::Template::Error:
No such file or directory @ rb_sysopen - public/server_rendering-0c232d693da2fd422ba9.js
```
The path `public/server_rendering-0c232d693da2fd422ba9.js` is not proper because my webpacker.yaml is following. `public/packs/server_rendering-0c232d693da2fd422ba9.js` is correct.
```
default: &default
source_path: app/javascript
source_entry_path: packs
public_output_path: packs
cache_path: tmp/cache/webpacker
```
Since it depends on the version of webpacker, I mofidied `lib/react/server_rendering/webpacker_manifest_container.rb`.
=> Improve the condition of webpacker major version

README.md
=> 📝 Document integrating with Turbolinks when imported with Webpacker

test/dummy_webpacker3/config/webpacker.yml, test/react/server_rendering/webpacker_manifest_container_test.rb
Closes #892 and #894 
https://github.com/reactjs/react-rails/pull/916/commits/415096a5b33b383eeb69b4d872f3cdc3f4e6454f
```
Now we need to set dev_server config to Rails.env.test
Error:
PagesControllerTest#test_it_mounts_components_from_the_dev_server:
RuntimeError: Failed to start dev server
/home/travis/build/reactjs/react-rails/test/support/webpacker_helpers.rb:65:in `with_dev_server'
/home/travis/build/reactjs/react-rails/test/react/rails/pages_controller_test.rb:32:in `block (2 levels) in <class:PagesControllerTest>'
Related to https://github.com/rails/webpacker/pull/1179
```
https://github.com/reactjs/react-rails/pull/916/commits/fa6e8f693baf7fed2ee62348b722531ad6627a78
```
Modify `WebpackerManifestContainerTest`
Failure:
WebpackerManifestContainerTest#test_it_loads_JS_from_the_webpac …
```
=> Modify the failing tests

README.md
Added subheading `#### Transform Plugin Options` to  `### Custom JSX Transformer` to outline how to add custom babel transform plugins to the asset pipeline
First time users who don't understand the structure of the gem have no way of knowing how to add transform plugins, or what version of babel react-rails is using to use the correct syntax.
Related to https://github.com/reactjs/react-rails/issues/401#issuecomment-411682998
=> Added documentation for babel transform plugins

lib/react.rb, test/react_test.rb
Adds support for React.camelize_props to camelize an instance of
ActionController::Parameters hash, so that permitted, strong parameters
in a Rails controller can be passed to a React component.
Resolves #931
=> Support camelizing ActionController::Parameters

lib/generators/react/install_generator.rb
Also, if someone is not using git, a .gitkeep feels odd, where a .keep seems fine.
=> Use .keep instead of .gitkeep to match Rails itself.

lib/generators/react/install_generator.rb, lib/generators/templates/server_rendering_pack.js, react-rails.gemspec, test/dummy_webpacker1/app/javascript/packs/server_rendering.js, test/dummy_webpacker2/app/javascript/packs/server_rendering.js, test/dummy_webpacker3/app/javascript/packs/server_rendering.js, test/generators/install_generator_webpacker_test.rb
Add semi-colons to generated JavaScript which is created when using the generator.
Seems like good practice and I always end up doing this myself after running the generator anyway for the sake of cleanliness. May as well fix it at the source, eh?
N/A
=> Add semi-colons to generated JavaScript

README.md
Skips this step that exists on the Webpacker instructions.
=> Add gem installation to Sprocket instructions.

README.md, lib/react-rails.rb, lib/react/rails/railtie.rb, lib/react/rails/test_helper.rb, test/dummy_sprockets/app/views/pages/show.html.erb, test/react/rails/test_helper_test.rb
```rb
test 'assert_react_component' do
get "/pages/1"
assert_equal 200, response.status
assert_react_component "GreetingMessage"
assert_react_component "GreetingMessage" do |props|
assert_equal "Bob", props[:name]
assert_equal "Last Bob", props[:last_name]
assert_equal "Bob", props[:info][:name]
assert_select "[id=?]", "component"
assert_select "[class=?]", "greeting-message"
end
end
```
=> Add assert_react_component method for test react_component render result

test/react/rails/pages_controller_test.rb
Tests were failing on Rails 5.2 because of an error introduced earlier where controller tests introduced did not make use of the provided params helpers.
=>  ✅ Update controller test to use `params:` when Rails 4+

lib/react/rails/test_helper.rb, test/react/rails/test_helper_test.rb
Last  commit https://github.com/reactjs/react-rails/commit/71ced0c2ac5b86c9393a5476436bf25a61786983 have bug.
When the page have more than one React Component, `assert_react_component` can't catch the next items.
=> Fix assert_react_component test helper for multiple components page

lib/react/rails/test_helper.rb, test/dummy_sprockets/app/views/pages/show.html.erb, test/dummy_webpacker1/app/views/pages/show.html.erb, test/dummy_webpacker2/app/views/pages/show.html.erb, test/dummy_webpacker3/app/views/pages/show.html.erb, test/react/rails/test_helper_test.rb
We need make sure the prop name is correct, because JavaScript used that it's case sensitive.
for example:
```erb
<%= react_component "InlineEditor", name: "comment[body_sml]", directUploadURL: rails_direct_uploads_url, blobURLTemplate: "/uploads/:id" %>
```
```jsx
const InlineEditor extends Component {
render() {
const { directUploadURL, blobURLTemplate } = this.props;
}
}
```
@BookOfGreg
=> Keep variable name case sensitive on assert_react_component props.

README.md
After https://github.com/reactjs/react-rails/pull/934/files#diff-3bb7346aca79d8142e16e61372bd04dcR14 was merged, i'm guessing that means Webpacker 4.x is actually supported now? README didn't say it was though.
Related:
- https://github.com/reactjs/react-rails/issues/918
- https://github.com/reactjs/react-rails/pull/934
- https://github.com/reactjs/react-rails/issues/939
=> Update README.md: Webpacker 4.x supported

lib/generators/react/component_generator.rb, lib/generators/templates/component.js.jsx.tsx
Allow the generation of typescript components by passing the `--ts` flag to the generator
resolves #965 
Also handles all the special prop types like `instanceOf`, `oneOf`, and `oneOfType`:
- Treat instanceOf prop types as reference to predefined types.
- Treat oneOf prop types as union types, and define the union type.
- Treat oneOfType prop types as union of primitives and custom types, and define both custom type and union type
```bash
$ bin/rails g react:component HelloWorld greeting:string \
'food:oneOf{meat,cheese,vegetable}' \
'cuisine:oneOfType{string,Food}' \
owner:instanceOf{Person} --ts
create  app/javascript/components/HelloWorld.tsx
```
```typescript
// app/javascript/components/HelloWorld.tsx
import * as React from "react"
type Food = 'meat' | 'cheese' | 'vegetable'
type …
```
=> Typescript component generator

VERSIONS.md
Update readme for using custom react version.
Resolves #993
=> clarify using custom react version

lib/react/rails/railtie.rb
Based on [this discussion in the rails repository](https://github.com/rails/rails/issues/31200) I determined that the latest version of `react-rails` (2.5.0, not present in 2.4.7) inadvertently causes `action_controller/test_case` to be required, which breaks `ActionController::Live` streaming in development and presumably production environments.
```ruby
/home/john/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/test_case.rb:23:in `<module:Live>'
/home/john/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/test_case.rb:18:in `<module:ActionController>'
/home/john/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/test_case.rb:13:in `<top (required)>' …
```
=> Only include React::Rails::TestHelper in test environment

CHANGELOG.md, package.json
Closes #1008 
This releases 2.6.0 of the UJS which releases the good work done on additional Turbolinks support.
=> Bump version for UJS to 2.6.0

react_ujs/index.js
Changed Let to Var to avoid breaking down in older browsers
Will fix  #1026
=> Changed Let to Var

react_ujs/src/events/turbolinks.js
UJS would mount non permanent react components multiple times when navigating away and then back to a page with one.
This was modified back in July in [this commit](https://github.com/reactjs/react-rails/commit/4dbcd6756dcd09c312abf95a73cbb6026f3f9a69#diff-caee293a420e16032c5cec4539620c8b). It appears as if it might have been modified unintentionally.
=> Call handleUnmount before rendering a new page

README.md
Modified installation instructions for Rails 6 🎉
Rails 6 now ships with webpacker as default JS compiler. See:  https://github.com/rails/rails/pull/33079
=> modified installation instructions for rails6

README.md
Adds a link to a sample Rails app that demonstrates HMR working with `react-rails` and adds a note of the present incompatibility of SSR and HMR.
=> 📝 Adds reference to sample repo demonstrating HMR

lib/react/jsx/sprockets_strategy.rb
RubyGems made a change that causes this error when you're on a beta version of Sprockets 4:
/home/vagrant/code/rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/react-rails-2.6.0/lib/react/jsx/sprockets_strategy.rb:40:in
`register_engine_with_mime_type': undefined method `register_engine' for Sprockets:Module (NoMethodError)
Here's the relevant commit:
https://github.com/rubygems/rubygems/commit/9836549344ace8ee822da0a5157d2810670e3bde#diff-94d386526b8b558035d4e4c7602d647c
And here's how the behavior of `Gemf::Version#<=>` has changed:
Before:
1:(main)> `gem --version`
=> "3.0.3\n"
2:(main)> Gem::Version.new("4.0.0.beta9") >= Gem::Version.new('4.x')
=> true
3:(main)> Gem::Version.new("4.0.0.beta9") >= Gem::Version.new('4.a')
=> true
After:
1:(main)> `gem --version`
=> "3.1.2\n"
2:(main)> …
=> Fix compatibility with beta versions of Sprockets

README.md
Update the description of the link to the online course  React on Rails at [learnetto](https://learnetto.com/users/hrishio/courses/react-rails-course) to not free, at it requires a purchase to access to the content.
=> Update README to mark the React on Rails Course as not free course

README.md
The project name has changed and the old url was an ad
None
=> Fix broken Hyperloop link in Readme

README.md
Recommend setting the `server_renderer_extensions` config option in the Typescript support section.
I experienced issues with changes to `tsx` and `ts` files not being properly updated in development. After loads of research on various levels of setup, I ran into [this issue](https://github.com/reactjs/react-rails/issues/1049#issuecomment-584993650), which thankfully had a fix (I felt equally stupid as the author). I'd say typescript support is incomplete without the `server_renderer_extensions` config. Anything else delivers a subpar development experience.
I hope you sill consider my addition to the README, and thanks for all the work you put into this lib 👍
=> Typescript support section: mention server_renderer_extensions

README.md
Added a note to point 2 of the header 'Get Started With Webpacker'.
For Rails 6, the line `gem 'webpacker'` is not needed in the gemfile, as
it is already added by default.
Leaving in the line generates an error when bundle install is run:
"You cannot specify the same gem twice with different version requirements. 
You specified: webpacker (>= 0) and webpacker (~> 4.0)"
=> 📝: Update README.md [ci skip]

README.md
Modified the Webpacker Section to reflect Rails 6 as the default.
*  Updated  the instructions for step 2 and modified the note attached to it. 
*  For step 3, merged instructions for Rails 6.x and 5.x, also removed the note there as it applied to step 4.
*  Converted step 4 to a note for Rails versions < 6.0, as it is not needed for Rails 6.x.
* Adjusted the remaining step numbers accordingly from [5, 8] to [4, 7].
=> 📝: Update README.md: Webpacker Section [ci skip]

gemfiles/rails_5.2_no_sprockets.gemfile.lock, gemfiles/rails_5.2_no_sprockets_webpacker_3.gemfile.lock, gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile.lock, gemfiles/rails_5.2_sprockets_3.gemfile.lock, gemfiles/rails_5.2_sprockets_4.gemfile.lock, package.json, test/dummy_webpacker3/package.json, test/dummy_webpacker3/yarn.lock, yarn.lock
Currently, if you pull down the app to do any work to contribute, and you run the tests, there are many errors that will pop up preventing you from being able to run the test suite.
The intention of this PR is to get the tests in working order so that we can build more tests to make sure that support for newer features, like webpack 5, are supported.
The issues lies in 2 main places:
1. mimemagic has yanked 3.3.3 (up through 3.3.7), so this upgrades the version for the tests to 3.3.10.
2. The current version of webpack-dev-server in the dummy app does not support webpack 3, which it is built for.  This change lowers the version of `webpack-dev-server` to `2.11.5`, which is the last update that supports webpack 3.
This PR purposefully does not add more tests, but I intend to make another …
=> Fix test suite

react_ujs/src/events/turbolinks.js
[As discussed in #1028](https://github.com/reactjs/react-rails/issues/1028#issuecomment-862475500), unmounting components on `turbolinks:before-render` prevents Turbolinks from restoring the scroll position when navigating back to pages with tall React components. This happens because Turbolinks tries to restore the scroll position before firing the `turbolinks:load` event. Since components were unmounted prior to this, the page might be much shorter than it will be after mounting components causing scroll position restoration to fail.
We've been running this in production for a week now and haven't noticed any issues caused by not unmounting components.
=> Don't unmount components on Turbolinks navigation

lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/index.js, react_ujs/src/renderHelpers.js
React 18 is changing the way that client-side components are rendered and hydrated. See https://github.com/reactwg/react-18/discussions/5
In order to create a path forward to using React 18, this adds support for both methods of hydrating and rendering so that newer React features can be used while maintaining full backward compatibility.
I did not add any specific tests for this because there was no clear way to test for different versions of React.  This seems like it should be explored in separately.
=> Support React 18's new client side rendering

package.json
Doesn't make any sense for a package to depend on itself.
If you import react_ujs manually from npm, the package-lock entry for it looks like
```
"react_ujs": {
"version": "2.6.2",
"resolved": "https://registry.npmjs.org/react_ujs/-/react_ujs-2.6.2.tgz",
"integrity": "sha512-4WH91hVZp0533LsTjbcd9uI9xS/7/e4QkFbDpDjy8Pr7GuUt1gE+cM0zml7Ii9aSUDl2A/zzkUrLN5X9akmViQ==",
"requires": {
"react_ujs": "^2.6.1"
}
}
```
=> Prevent react_ujs from depending on itself

README.md
Took me a while to figure out the path to override the generator templates till I dug through the Rails source, so suggest to make a note of it in the documentation. Potentially a fix for https://github.com/reactjs/react-rails/issues/1067.
=> Add instructions on overriding component templates

test/dummy_webpacker3/package.json, test/dummy_webpacker3/yarn.lock
Reverts reactjs/react-rails#1150. See https://github.com/reactjs/react-rails/pull/1198#issuecomment-1229123819 for reasoning. Hopefully we'll be able to upgrade things soon!
=> Revert "Bump webpack-dev-server from 2.11.5 to 3.1.11 in /test/dummy_webpacker3"

test/dummy_sprockets/package.json, test/dummy_sprockets/yarn.lock
Reverts reactjs/react-rails#1158. See https://github.com/reactjs/react-rails/pull/1158#issuecomment-1242626994 for reasoning. Hopefully we'll be able to upgrade things soon!
=> Revert "Bump node-sass from 4.13.1 to 7.0.0 in /test/dummy_sprockets"

VERSIONS.md
:memo: Fix VERSIONS.md formatting
[ci skip]
A missing pipe in the table header was causing the table to render incorrectly.
N/A
=> :memo: Fix VERSIONS.md formatting

lib/react.rb, test/react_test.rb
This solves the case where we want to camelize_props, but those props aren't explicitly a hash or array (for example `ActiveModel::Serializer`, `Representable`, `ActionController::Parameters`, etc.
As mentioned about, I'm making the assumption that ActiveSupport is loaded since this is within Rails, but let me know if that's not a valid assumption
Also, thoughts on simplifying it even further? If we know that ActiveSupport is defined, we could just use `#deep_transform_keys` as so
```ruby
def self.camelize_props(props)
props_as_json = props.as_json
case props_as_json
when Hash
props_as_json.deep_transform_keys { |key| key.to_s.camelize(:lower) }
when Array
props.map { |prop| camelize_props(props) }
else
props
end
end
=> Camelize all props that can be converted to JSON

CHANGELOG.md, README.md, lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/index.js
This enables us to easily override `getConstructor` to not use global
fallback, avoiding the all-consuming `try...catch`.
Here's the context:
Quoting https://github.com/reactjs/react-rails/issues/264#issuecomment-552326663
> Regarding `Encountered error "#<ExecJS::ProgramError: Invariant
> Violation: Element type is invalid: ...`:
>
> I think one of the core issues is that [module lookup uses
> `try...catch`](https://github.com/reactjs/react-rails/blob/master/react_ujs/src/getConstructor/fromRequireContextWithGlobalFallback.js#L11-L23).
> While the errors are logged to the console shim, that typically doesn't
> help as a later error (such as the invariant violation) will lead to a
> fatal error (triggering a 500). If that could be refactored to be a bit
> more intentional based on …
=> Expose all built-in options for `getConstructor`

CHANGELOG.md, lib/generators/react/install_generator.rb
The default `config/webpacker.yml` on `shakapacker` version 6.x is set to absolute path of `/` which points to root of the filesystem. This breaks installation process of react-rails.
This commit is a workaround for Shakapacker 6.x. Version 7 is expected to resolve this issue.
Related issues:
- [Upgrade docs to refer to Shakapacker](https://github.com/reactjs/react-rails/issues/1211)
- [Absolute source_entry_path in webpacker.yml refers to filesystem root](https://github.com/shakacode/shakapacker/pull/205)
=> Update webpacker.yml in react:install generator

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, README.md
Updated following files to refer to Shakapacker instead of Webpacker:
- README.md
- CONTRIBUTING.md
- GitHub issue template
**Note:** #1216 automates replacing `/` with `packs` in `webpacker.yml`. If that PR gets merged, this PR needs a minor update.
Closes #1211
=> Update readme to refer to shakapacker

react_ujs/src/renderHelpers.js
We are experiencing a breaking change when using react_ujs@2.6.2 (2.6.1 worked fine) when built into a Vite project. ReactDOM is not defined when attempting to import it in `renderHelpers.js`. Through changing the code in node_modules for react_ujs, we have found that changing ReactDOM to an ESM import resolves the issue. This is because build tools often (I recall having this issue in the past with Webpack) have trouble mixing requires (non-ESM) with ESM exports. This PR resolves this issue by changing to an import.
The other option, to make this code consistent with the rest of this project, would be to switch the named exports to a `module.exports` object. If that is preferred, I can update this PR.
=> Switch ReactDOM to ESM import to match ESM exports

CHANGELOG.md, react_ujs/src/reactDomClient.js, react_ujs/src/renderHelpers.js
This PR fixes the warning related to loading `react-dom` in React 18.
Closes #1258
=> Load react-dom correctly based on React version

README.md
Added documentation for suppressing warning message
=> Update documentation for suppressing warning related to `react-dom/client`

.github/workflows/ruby.yml
To run CI on PR made by contributors other than the official team, we need to include pull_request in the list of triggers.
=> Include PR as a trigger for CI

README.md
This PR updates documentation for **version 2.7** to cover Shakapacker 7.
Notice: this is for version 2.7 branch. For version 3 we need more updates.
=> Update docs to cover sp7 - for react-rails v2.7

gemfiles/base.gemfile.lock, gemfiles/shakapacker.gemfile.lock, gemfiles/sprockets_3.gemfile.lock, gemfiles/sprockets_4.gemfile.lock
Update `Gemfile.lock` of tests to match version 3.
@Judahmeek 
Need to merge this to keep #1293 cleaner.
=> Update lock files in tests for version 3

CHANGELOG.md, lib/generators/react/component_generator.rb, lib/generators/templates/component.es6.tsx, test/generators/ts_es6_component_generator_test.rb
Thank you for great integration rails and react. I use react-rails recently and I notice that I can't use `--ts` and `--es6` same time. What about making these two available at the same time?
This is actual generated file
`rails g react:component HelloWorld greeting:string --ts --es6`
```tsx
import * as React from "react"
interface IHelloWorldProps {
greeting: string;
}
const HelloWorld = (props: IHelloWorldProps) => {
return (
<React.Fragment>
Greeting: {props.greeting}
</React.Fragment>
)
}
export default HelloWorld
```
=> Make generator es6 and ts usable at same time

.github/workflows/rubocop.yml, .github/workflows/ruby.yml
Disabling persisted credentials is a nice-to-have security improvement - it's very unlikely to ever actually be exploitable for this codebase, but might as well disable it nonetheless; see https://github.com/actions/checkout/issues/485 for more.
=> ci: update `actions/checkout` and disable persisted git credentials

README.md, docs/common-errors.md
Add documentation for addressing errors when putting tests in `app/javascript/component`.
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
Closes #1095
=> docs: add solution for tests in component dir

.github/workflows/rubocop.yml
Currently rubocop failures are not properly coming through on pull requests because the workflow only runs on push - this is why e.g. #1320 was able to slip through
=> ci: run `rubocop` on pull requests

package.json, react-builds/package.json, react-builds/yarn.lock, test/dummy/package.json
With #1306 landed we now support any of the main package managers which includes for our internal plumbing, and since we're not specifying a package manager `npm` is being used by default which is highlighting a peer dependency conflict with `react-transition-group` - it turns out that we don't actually need this package anymore so it can just go, but I've also explicitly set the `packageManager` to be `yarn` since that is what was being used before.
Since this is also touching the `package.json` files, I figured it would be a good time to slip in running `sort-package-json` for consistency.
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
=> chore: specify `yarn` as package manager and remove unused dependency

.github/workflows/rubocop.yml, .github/workflows/ruby.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, docs/component-generator.md, docs/get-started.md, docs/migrating-from-react-rails-to-react_on_rails.md, docs/server-side-rendering.md, docs/upgrading.md
This is the canonical default branch these days - might as well get the switch over with; once this is merged ideally the `master` branch should be renamed to `main` using GitHub's UI so that workflow runs and other such logs are retained.
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
=> chore: switch default branch to `main`

docs/get-started.md
Using webpackconfig throws a deprecation warning and encourages user to use generateWebpackConfig() instead. Updates docs to avoid this deprecation warning. 
```
Output: 
$ ./bin/shakapacker-dev-server
⚠️
DEPRECATION NOTICE:
The 'webpackConfig' is deprecated and will be removed in a future version.
Please use 'globalMutableWebpackConfig' instead, or use
'generateWebpackConfig()' to avoid unwanted config mutation across the app.
For more information, see version 7 upgrade documentation at:
https://github.com/shakacode/shakapacker/blob/master/docs/v7_upgrade.md
```
- [x ] Add/update test to cover these changes
- [ x] Update documentation
- [ x] Update CHANGELOG file
=> Update get-started.md | Removes deprecation warning for webpackconfig in favor of generateWebpackConfig

README.md
Add HoneyBadger Logo to the list of supporters in README.
=> Add honeybadger logo to README.md
