reactjs/react-rails

react-rails.gemspec, test/jsxtransform_test.rb
Follow up to #139, using 0.12 as a target branch instead of master.
See previous discussion at #139.
=> Upgrade react-source to 0.12.2

.travis.yml
before: [about 4 min](https://travis-ci.org/tricknotes/react-rails/builds/47638822)
after: [about 3 min](https://travis-ci.org/tricknotes/react-rails/builds/47639547)
=> Faster test on Travis CI

README.md
As per #177. I think this makes things clearer.
=> Readme: clarify Jbuilder root node recommendation

react-rails.gemspec
We already have a `0.13` branch that uses 13, but it's time to update master too I think
=> update to React 0.13.1

README.md, lib/react/jsx.rb, lib/react/jsx/template.rb, lib/react/rails/railtie.rb, test/dummy/config/application.rb
=> add jsx_transform_options

lib/generators/templates/component.js.jsx
=> Fixed bug with generating unusable components

react-rails.gemspec, test/test_helper.rb
=> Codeclimate coverage

README.md
Added a link to the React Getting Started guide in the readme for developers checking out React for the first time.
=> Add getting started guide

README.md
@rmosolgo Thanks so much for considering my PR! :smile:
=> Update README.md with Related Projects section

lib/assets/javascripts/react_ujs.js.erb
quick fix for IE8 without jQuery...which you probably wont/cant have with server side render
=> add support for IE8 without jQuery

lib/react/server_rendering/sprockets_renderer.rb, lib/react/server_rendering/sprockets_renderer/console_polyfill.js, lib/react/server_rendering/sprockets_renderer/console_replay.js
One small PR to begin chipping away at 2.0.0! #448
=> Use .js files for CONSOLE_POLYFILL and CONSOLE_REPLAY

lib/generators/react/install_generator.rb, test/generators/install_generator_test.rb
Updated checks to be totally in sync and also added handling for extra spaces in every possible place. Fixes #462
=> #462 Fixed updating application.js whith messed-up require markers

lib/react/rails/railtie.rb, test/dummy/config/initializers/react.rb, test/react/rails/view_helper_test.rb
=> Run initializer blocks after :load_config_initializers

test/test_helper.rb
Try to get this working again ...
=> update codeclimate test reporter

README.md, lib/react/rails/controller_renderer.rb, test/dummy/app/controllers/server_controller.rb, test/dummy/config/routes.rb, test/server_rendered_html_test.rb
=> Controller preprender: false

lib/react/server_rendering/bundle_renderer.rb, lib/react/server_rendering/bundle_renderer/console_reset.js, test/dummy/app/assets/javascripts/components/TodoList.js.jsx, test/react/server_rendering/console_replay_test.rb
=> fix(console_replay) clear state between renders

.travis.yml, Appraisals, gemfiles/rails_5.1_sprockets_4.gemfile, lib/react/rails/railtie.rb, test/dummy/package.json, test/dummy/yarn.lock, test/react/rails/pages_controller_test.rb, test/test_helper.rb
=> feat(Rails) support 5.1

lib/assets/javascripts/react_ujs.js, react_ujs/dist/react_ujs.js, react_ujs/src/getConstructor/fromRequireContextWithGlobalFallback.js, test/react/server_rendering/bundle_renderer_test.rb
Right now, if there's an error when building a node module, you never see it :(
=> feat(ujs) show errors when component can't be loaded

lib/generators/react/install_generator.rb
=> Call the yarn executable directly

test/generators/coffee_component_generator_test.rb
In #799 @ViXP corrects how Coffeescript works, but I forgot to update a test before merge to master. My bad!
This PR corrects the related test.
=> Correct CoffeeGeneratorTest

README.md
https://github.com/reactjs/react-rails/issues/702
=> Updated README.md to include capitalization gotchas

lib/react/jsx/jsx_transformer.rb
Just a small tweak to a code comment to make the codebase more inclusive 😊
=> Remove male pronoun in code comment

yarn.lock
run rake task `ujs:update` to ensure dependencies are up to date.
=> rake ujs:update

README.md
=> Fix small typo: HRM --> HMR

CHANGELOG.md, VERSIONS.md, lib/react/rails/version.rb
Note the major changes in changelog.
=> Prep for 2.6

test/dummy_sprockets/yarn.lock, test/dummy_webpacker1/yarn.lock, test/dummy_webpacker2/yarn.lock, test/dummy_webpacker3/yarn.lock
Js deps need to be kept up to date in test folders also.
=> yarn upgrade dummy apps

README.md
Added instructions for how to properly call nested components to the project read me.
This is a simple read me change that will help new gem users.
=> Add nested component call info

README.md
=> Trivial typofix

lib/react/server_rendering/webpacker_manifest_container.rb
See [this issue + comment](https://github.com/reactjs/react-rails/issues/1157#issuecomment-1048168829)
=> Add support for shakapacker in server rendering

README.md
=> Update status bage to point to GitHub Actions

.github/workflows/ruby.yml
Set Node options for OpenSSL legacy provider.
Reference: https://github.com/webpack/webpack/issues/14532#issuecomment-947012063
=> Fix CI failure

.github/PULL_REQUEST_TEMPLATE.md
Fix typo and remove unnecessary note
=> Fix typo and remove unnecessary note

test/dummy/config/webpack/webpack.config.js
We had to get failing tests for this typo but we didn't
=> Fix typo in webpack.config.js of dummy app

CHANGELOG.md
- Update the Changelog to have correct entry for version 3.0.0
- Correct links
=> Update changelog for version 3

README.md
Just fixes a small but noticeable typo in the README.
n/a
=> Fix typo in README Resources header
